# Generated by Django 2.0 on 2018-12-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0003_auto_20181228_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opcoes',
            new_name='Opcao',
        ),
    ]
