# Generated by Django 2.0 on 2018-12-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opcoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcao', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_questao', models.CharField(max_length=250)),
                ('data_publcacao', models.DateTimeField(verbose_name='data publicada')),
            ],
        ),
        migrations.AddField(
            model_name='opcoes',
            name='quastao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisas.Questao'),
        ),
    ]
